name: Build C# Windows EXE (Lightweight)

on:
  push:
    branches: [ "csharp-version" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Compile and Pack C# App
      run: |
        # Собираем ультра-легкий файл (без встроенной платформы)
        dotnet publish SentinelTool.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true --self-contained false -o output_folder

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: Sentinel-CSharp-Light
        path: output_folder\SentinelTool.exe
